### ISSUE TITLE
Problem while fuzzing DCMTK

### ISSUE THREAD

**Issue by Br1m4zz** [bajinsheng/SFuzzer#9]
Hi ,
I am appreciating your work, and I have tried to reproduce result in fuzzing DCMTK, but I met some trouble while running your fuzzer:

## why exit normally without continuing fuzzing?
 After successfully building the fuzzer, I try to run it with the following command:
``` 
 ./dcmqrscp -close_fd_mask=3 -detect_leaks=0 -ignore_ooms=1 -ignore_timeouts=1  ../../../in-dicom-origin/ -- --single-process
```
it exited normally with some output like this, but without continuously fuzzing. :
```
INFO: Seed: 1601392419
INFO: Loaded 1 modules   (59454 inline 8-bit counters): 59454 [0xdf7c40, 0xe0647e), 
INFO: Loaded 1 PC tables (59454 PCs): 59454 [0xe06480,0xeee860), 
INFO:       11 files found in ../../../in-dicom-origin/
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 17755 bytes
INFO: seed corpus: files: 11 min: 301b max: 17755b total: 86977b rss: 44Mb
#12     INITED cov: 875 ft: 1238 corp: 10/84Kb exec/s: 0 rss: 49Mb states: 242 leaves: 9
#13     NEW    cov: 875 ft: 1243 corp: 11/101Kb lim: 17755 exec/s: 0 rss: 50Mb states: 242 leaves: 9 L: 17755/17755 MS: 1 CMP- DE: "\xfe\xff\xff\xff"-
(exited normally)
```

So I attach to gdb and make  breakpoint at  `HonggfuzzNetDriver_main`.  The fuzzer continued running. and produce following thread:
```
(gdb) info threads 
  Id   Target Id         Frame 
* 1    Thread 0x7f9530707800 (LWP 200361) "dcmqrscp" fuzzer::FuzzerDriver (argc=<optimized out>, argv=<optimized out>, Callback=<optimized out>) at ./FuzzerDriver.cpp:823
  2    Thread 0x7f952b8ff700 (LWP 201238) "dcmqrscp" 0x00007f952ef2484d in poll () at ../sysdeps/unix/syscall-template.S:84
  3    Thread 0x7f95293c4700 (LWP 203222) "dcmqrscp" 0x00007f952eef538d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
``` 

When stop at  /sfuzzer-evaluate/FuzzerDriver.cpp
```
906       F->Loop(CorporaFiles);
```
it output ：
```
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 17755 bytes
INFO: seed corpus: files: 11 min: 301b max: 17755b total: 86977b rss: 55Mb
#2      pulse  ft: 760 exec/s: 0 rss: 55Mb states: 70 leaves: 3
#4      pulse  cov: 784 ft: 885 corp: 2/602b exec/s: 0 rss: 55Mb states: 120 leaves: 5
#8      pulse  cov: 846 ft: 1064 corp: 5/12059b exec/s: 0 rss: 55Mb states: 179 leaves: 7
#12     INITED cov: 875 ft: 1232 corp: 9/74Kb exec/s: 0 rss: 55Mb states: 242 leaves: 9
```
and gdb grab thread exited
```
[Thread 0x7f95293c4700 (LWP 203222) exited]  // syscall-template.S:84
[Thread 0x7f9530707800 (LWP 200361) exited]  // FuzzerDriver.cpp:823
```
and then `[Inferior 1 (process 200361) exited normally]`.

add breakpoint at ` F->Loop(CorporaFiles);` ,and step into it, at  `ReadAndExecuteSeedCorpora(CorporaFiles);`(./FuzzerLoop.cpp:905) , it output
```
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 17755 bytes
INFO: seed corpus: files: 17 min: 301b max: 17755b total: 151635b rss: 44Mb
#2      pulse  ft: 736 exec/s: 0 rss: 45Mb states: 70 leaves: 3
#4      pulse  cov: 784 ft: 839 corp: 2/602b exec/s: 0 rss: 46Mb states: 112 leaves: 5
#8      pulse  cov: 865 ft: 990 corp: 5/1807b exec/s: 0 rss: 46Mb states: 127 leaves: 6
#16     pulse  cov: 926 ft: 1356 corp: 11/84Kb exec/s: 0 rss: 50Mb states: 249 leaves: 10
#18     INITED cov: 926 ft: 1365 corp: 13/119Kb exec/s: 0 rss: 51Mb states: 249 leaves: 10
(I give initial 4 seeds)
```
and exited at ` Min(MaxMutationLen, Max(size_t(4), Corpus.MaxInputSize()));`(ln 912).  Stepping in, at 
```
(FuzzerCorpus.h: 191~196)
  size_t MaxInputSize() const {
    size_t Res = 0;
    for (auto II : Inputs)
        Res = std::max(Res, II->U.size());
    return Res;
  }
```
current backtrace:
```
#0  0x00000000009d881b in fuzzer::InputCorpus::MaxInputSize (this=<optimized out>)
#1  fuzzer::Fuzzer::Loop (this=<optimized out>, CorporaFiles=...) at ./FuzzerLoop.cpp:912
#2  0x00000000009c4ed4 in fuzzer::FuzzerDriver (argc=<optimized out>, argv=<optimized out>, Callback=<optimized out>)
    at ./FuzzerDriver.cpp:906
#3  0x00000000009bf7f3 in main (argc=1699954145, argv=<error reading variable: Cannot access memory at address 0x0>)
    at ./FuzzerMain.cpp:20
```

setting breakpoint at ./FuzzerCorpus.h:194 and continue, it hit this breakpoint a few times and exited normally
```
Thread 1 "dcmqrscp" hit Breakpoint 5, fuzzer::InputCorpus::MaxInputSize (this=<optimized out>) at ./FuzzerCorpus.h:194
194             Res = std::max(Res, II->U.size());
(gdb) 
Continuing.

Thread 1 "dcmqrscp" hit Breakpoint 5, fuzzer::InputCorpus::MaxInputSize (this=<optimized out>) at ./FuzzerCorpus.h:194
194             Res = std::max(Res, II->U.size());
(gdb) 
Continuing.
[Thread 0x7f2f602c4700 (LWP 231525) exited]
[Thread 0x7f2f627ff700 (LWP 231524) exited]
[Inferior 1 (process 231464) exited normally]
```
and I only add breakpoint at `NewCov = RunOne(CurrentUnitData, Size, /*MayDeleteFile=*/true, &II,`(./FuzzerLoop.cpp:770)

gdb sometimes catch following error:
```
Thread 2 "dcmqrscp" received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7f32a49ff700 (LWP 243876)]
0x00007f32a8fc44bd in write () at ../sysdeps/unix/syscall-template.S:84
84      ../sysdeps/unix/syscall-template.S: No such file or directory.
```

the breakpoint was hit a few times and the fuzzer exit again.

So why the fuzzer exited normally without continuing fuzzing?

## How sgfuzz handle inputs 
and one more questions, is sgfuzz send all requests in seed in one connection without receiving any response messages?

**Comment by bajinsheng** [comment]
Which version of Dcmtk do you use? It is probably a conflict between Dcmtk and SGFuzz, because both of them are running the same process. I would suggest you gdb the Dcmtk to check what is happening.


For my previous experiments, I patched Dcmtk to avoid conflicts:
```
diff --git a/dcmqrdb/apps/dcmqrscp.cc b/dcmqrdb/apps/dcmqrscp.cc
index 0ddc933c1..edc1bc085 100644
--- a/dcmqrdb/apps/dcmqrscp.cc
+++ b/dcmqrdb/apps/dcmqrscp.cc
@@ -83,7 +83,7 @@ static char rcsid[] = "$dcmtk: " OFFIS_CONSOLE_APPLICATION " v"
 
 #define APPLICATIONTITLE "DCMQRSCP"
 
-const char *opt_configFileName = DEFAULT_CONFIGURATION_DIR "dcmqrscp.cfg";
+const char *opt_configFileName = "./dcmqrscp.cfg";
 OFBool      opt_checkFindIdentifier = OFFalse;
 OFBool      opt_checkMoveIdentifier = OFFalse;
 OFCmdUnsignedInt opt_port = 0;
diff --git a/dcmqrdb/libsrc/dcmqrsrv.cc b/dcmqrdb/libsrc/dcmqrsrv.cc
index 7f01409c5..73dd2c450 100644
--- a/dcmqrdb/libsrc/dcmqrsrv.cc
+++ b/dcmqrdb/libsrc/dcmqrsrv.cc
@@ -966,6 +966,7 @@ OFCondition DcmQueryRetrieveSCP::waitForAssociation(T_ASC_Network * theNet)
     char                buf[BUFSIZ];
     int timeout;
     OFBool go_cleanup = OFFalse;
+    OFBool go_fuzzercleanup = OFTrue;
 
     if (options_.singleProcess_) timeout = 1000;
     else
@@ -1083,6 +1084,7 @@ OFCondition DcmQueryRetrieveSCP::waitForAssociation(T_ASC_Network * theNet)
         {
             /* don't spawn a sub-process to handle the association */
             cond = handleAssociation(assoc, options_.correctUIDPadding_);
+            go_fuzzercleanup = OFFalse;
         }
 #ifdef HAVE_FORK
         else
@@ -1114,7 +1116,7 @@ OFCondition DcmQueryRetrieveSCP::waitForAssociation(T_ASC_Network * theNet)
 
     // cleanup code
     OFCondition oldcond = cond;    /* store condition flag for later use */
-    if (!options_.singleProcess_ && (cond != ASC_SHUTDOWNAPPLICATION))
+    if (go_fuzzercleanup)
     {
         /* the child will handle the association, we can drop it */
         cond = ASC_dropAssociation(assoc);
@@ -1128,7 +1130,7 @@ OFCondition DcmQueryRetrieveSCP::waitForAssociation(T_ASC_Network * theNet)
             DCMQRDB_ERROR("Cannot Destroy Association: " << DimseCondition::dump(temp_str, cond));
         }
     }
-
+    
     if (oldcond == ASC_SHUTDOWNAPPLICATION) cond = oldcond; /* abort flag is reported to top-level wait loop */
     return cond;
 }
```

**Comment by Br1m4zz** [comment]
Thank you for your patch and it works! 
The commit version I use is 7f8564c and I apply the patch on libsrc/dcmqrsrv.cc
It's probabaly because thread conflicts between libfuzzer and the target that  leads to the exit
